version: '3'

services:
  server:  
    build:
      context: ./Server
      dockerfile: Dockerfile
    restart: unless-stopped
    ports: 
      - '5000:5000'
    volumes:
      - ./Server:/src
    networks:
      - app-network

  nginx:
    image: webapp-nginx
    build:
      context: ./Nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - server
    networks:
      - app-network

  postgres:
    image: postgres:10.5
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - '5432'
    ports:
      - 5432:5432
    links:
      - server
    networks:
      - app-network
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080

networks:
  app-network:
    driver: bridge
